apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web3-deployment
  labels:
    app: hello-web3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-web3
  template:
    metadata:
      labels:
        app: hello-web3
    spec:
      containers:
      - name: hello-web3
        image: hello-web3:latest
        ports:
        - containerPort: 80
